spring.application.name=stonewesthomes
# ===============================
# DATABASE CONNECTION (Internal Docker)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/realestate_db
spring.datasource.username=postgres
spring.datasource.password=3570
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# PERFORMANCE (Virtual Threads)
# ===============================
spring.threads.virtual.enabled=true

# ===============================
# SERVER
# ===============================
server.port=8080